In [2]:
import pandas as pd
import re

In [3]:
df = pd.read_csv("hasil_preprocessing.csv", usecols=["tweet_stemming","sentimen"])
df.columns = ["sentimen", "tweet"]
df.head(10)

  sentimen                                              tweet
0   netral  ['sehat', 'vaksin', 'kini', 'viralkan', 'cerit...
1  negatif  ['sekarang', 'i', 'faham', 'kenapa', 'org', 't...
2  negatif  ['tengok', 'doktor', 'pun', 'ada', 'yang', 'ce...
3   netral  ['side', 'effects', 'vaksin', 'ini', 'kalau', ...
4  positif  ['kisah', 'kami', 'positif', 'covid', 'di', 'b...
5  negatif  ['bila', 'orang', 'pakar', 'ubat', 'famili', '...
6  negatif  ['lately', 'ini', 'banyak', 'dengar', 'orang',...
7  negatif  ['frontliner', 'dapat', 'pfizer', 'kami', 'dap...
8  negatif  ['berat', 'lah', 'sek', 'ini', 'menate', 'mano...
9  positif  ['antara', 'negara', 'keluar', 'vaksin', 'dan'...

In [4]:
df['sentimen'].value_counts(ascending=True)

netral     79
negatif    81
positif    83
Name: sentimen, dtype: int64

In [5]:
p_netral = 79/243
p_negatif = 81/243
p_positif = 83/243
print(p_netral)
print(p_negatif)
print(p_positif)

0.32510288065843623
0.3333333333333333
0.34156378600823045

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
data_netral = [row['tweet'] for index,row in df.iterrows() if row["sentimen"]=='netral']

vec_netral = CountVectorizer()
d_netral = vec_netral.fit_transform(data_netral)
tdm_netral = pd.DataFrame(d_netral.toarray(), columns=vec_netral.get_feature_names())

tdm_netral

,000004,00b2,120,17,1st,2018introducer,2019,201ckalau,201d,2021,...,vs,wanita,warga,we,xhahaahah,xtaulah,ya,yakni,yang,zeneca
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
77,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
data_negatif = [row['tweet'] for index,row in df.iterrows() if row["sentimen"]=='negatif']

vec_negatif = CountVectorizer()
d_negatif = vec_negatif.fit_transform(data_negatif)
tdm_negatif = pd.DataFrame(d_negatif.toarray(), columns=vec_negatif.get_feature_names())

tdm_negatif

,00b2,10,100,1000,120,18,19,1909,2018org,2019,...,wibu,with,wkwkwkwk,woi,xnak,ya,yahudi,yang,you,zaman
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
77,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
78,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
79,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [13]:
data_positif = [row['tweet'] for index,row in df.iterrows() if row["sentimen"]=='positif']

vec_positif = CountVectorizer()
d_positif = vec_positif.fit_transform(data_positif)
tdm_positif = pd.DataFrame(d_positif.toarray(), columns=vec_positif.get_feature_names())

tdm_positif

,10k,120,15,1535hrs,200,2018introducer,2018vaksin,2019,2019s,201crakyat,...,warga,warwar,whatsapp,wife,within,ya,yakin,yang,yo,you
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
79,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
80,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
82,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [42]:
kata_netral = vec_netral.get_feature_names();
hitung_kata_netral = d_netral.toarray().sum(axis=0)
frek_netral = dict(zip(kata_netral,hitung_kata_netral))
#frek_netral

In [41]:
kata_negatif = vec_negatif.get_feature_names();
hitung_kata_negatif = d_negatif.toarray().sum(axis=0)
frek_negatif = dict(zip(kata_negatif,hitung_kata_negatif))
#frek_negatif

In [40]:
kata_positif = vec_positif.get_feature_names();
hitung_kata_positif = d_positif.toarray().sum(axis=0)
frek_positif = dict(zip(kata_positif,hitung_kata_positif))
#frek_positif

In [39]:
peluang_netral = []
for kata, count in zip(kata_netral,hitung_kata_netral):
    peluang_netral.append(count/len(kata_netral))
angka_net = dict(zip(kata_netral,peluang_netral))
#angka_net

In [38]:
peluang_negatif = []
for kata, count in zip(kata_negatif,hitung_kata_negatif):
    peluang_negatif.append(count/len(kata_negatif))
angka_neg = dict(zip(kata_negatif,peluang_negatif))
#angka_neg

In [37]:
peluang_positif = []
for kata, count in zip(kata_positif,hitung_kata_positif):
    peluang_positif.append(count/len(kata_positif))
angka_pos = dict(zip(kata_positif,peluang_positif))
#angka_pos

In [26]:
from nltk.tokenize import word_tokenize
import string

In [35]:
df_test = pd.read_csv("testing data.csv")
df_test.head()

                                               tweet
0    1 penyuntik vaksin perlu menunjukkan jarum s...
1    helloo my 83yo grandma dah complete vaksin a...
2    punyalah tak malu berlagak macam tu sekali d...
3    tempahan vaksin astrazeneca untuk warga emas...
4    while my mom yang taknak cucuk vaksin d83e d...

In [36]:
def word_rekonizing(text):
  return word_tokenize(text)

df_test['tweet'] = df_test['tweet'].apply(word_rekonizing)
print(df_test['tweet'].head())

0    [1, penyuntik, vaksin, perlu, menunjukkan, jar...
1    [helloo, my, 83yo, grandma, dah, complete, vak...
2    [punyalah, tak, malu, berlagak, macam, tu, sek...
3    [tempahan, vaksin, astrazeneca, untuk, warga, ...
4    [while, my, mom, yang, taknak, cucuk, vaksin, ...
Name: tweet, dtype: object

In [ ]:
prob_netral_with_ls = []
for word in df_test:
    if word in frek_netral.keys():
        count = frek_netral[word]
    else:
        count = 0
    prob_netral_with_ls.append((count + 1)/)